apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-appsets-test
spec:
  generators:
  - list:
      elements:
      - cluster: k3s-cluster1
        url: https://192.168.1.49:6443
      - cluster: k3s-cluster2
        url: https://192.168.1.51:6443
      - cluster: k3s-cluster3
        url: https://192.168.1.50:6443
  template:
    metadata:
      name: '{{cluster}}-argocd-appsets'
    spec:
      project: default
      source:
        repoURL: https://github.com/deegbo/argocd-appSet.git
        targetRevision: HEAD
        path: 'argocd-appsets/{{cluster}}'
      destination:
        server: '{{url}}'
        namespace: nginx
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
